version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: authenticate
    environment:
      POSTGRES_DB: authenticate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data